on:
  - push
  - pull_request

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 9.1.2
          run_install: true
      - run: pnpm build
      - name: jsr publish dry-run
        run: npx jsr publish --dry-run
        working-directory: packages/chrono-sdk
      - if: github.event_name != 'pull_request'
        uses: actions/upload-artifact@v4
        with:
          name: chrono-extension
          path: build
