name: publish

on:
  push:
    branches:
      - "main"

jobs:
  jsr:
    uses: planetarium/.github/.github/workflows/publish_jsr.yaml@2b72e856e480478f6b9dbfa944f43e985cd83f5f
    with:
      working_directory: "packages/chrono-sdk"
      pnpm_version: "9.1.2"
