name: publish

on:
  push:
    branches:
      - "main"

jobs:
  jsr:
    uses: planetarium/.github/.github/workflows/publish_jsr.yaml@7da1714cbc9554aa17a19bc6477b8b067f714ea7
    with:
      working_directory: "packages/chrono-sdk"
      pnpm_version: "9.1.2"
